(define (domain turmultimodal-adl)
	(:requirements :adl :typing) 
  (:types pessoa bicicleta estacoes pontos)
  (:predicates
    (adj ?estacao-1 ?estacao-2 - estacoes)
    (adj-2 ?estacao-1 - estacoes ?ponto-1 - pontos)
    (at ?who - pessoa ?where)
    (free ?bicicleta-1 - bicicleta ?estacao-1 - estacoes)
    (ocupied ?who - pessoa ?bike - bicicleta)
    (visit ?who - pessoa ?which - pontos)
    (with ?who - pessoa) ;esta com bicicleta
  )
  (:action pegar-bicicleta
  	:parameters (?who - pessoa ?where - estacoes ?bike - bicicleta)
    :precondition (and  (not (with ?who))
                        (free ?bike ?where)
                        (at ?who ?where)
                  )
    :effect (and  (with ?who)
                  (at ?who ?where)
                  (not (free ?bike ?where))
                  (ocupied ?who ?bike)
            )
  )
  (action entregar-bicicleta
  	:parameters(?who - pessoa ?where - estacoes ?bike - bicicleta)
    :precondition(and (with ?who)
                      (at ?who ?where)
                      (ocupied ?who ?bike)
                  )
    :effect(and (not (with ?who))
                (at ?who ?where)
                (free ?bike ?where)
                (not (ocupied ?who ?bike))
            )
  )
  
  (action esperar5min
  	:parameters()
    :precondition()
    :effect()
  )
  
  (action caminhar
  	:parameters(?who - pessoa ?where - estacoes ?which - pontos)
    :precondition((and (not (with ?who)
                  )
                  (or (at ?who ?where)
                      (at ?who ?which)
                  )
                  )
    :effect((or (and (not (at ?who ?where))
                     (adj-2 ?where ?which) 
                     (at ?who ?which)
                )
                (and  (not (at ?who ?which))
                      (adj-2 ?where ?which)
                      (at ?who ?where)
                )
            )
          )
  )
  
  (action visitar-ponto
  	:parameters(?who - pessoa ?where - estacoes ?which - pontos)
    :precondition(and (not (with ?who))
                      (not (visit ?who ?which))
                      (at ?who ?where)
                      (adj-2 ?where ?which)
                  )
    :effect(and (visit ?who ?which)
                (not (at ?who ?where))
                (at ?who ?which)
                ;gastou 5 minutos??
          )
  )
  
  (action pedalar
  	:parameters()
    :precondition()
    :effect()
  )
) 